/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSection: typeof import('./src/components/AppSection.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HowToUse: typeof import('./src/components/HowToUse.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parse_c1d94c6a613ac216ea8a78424965ec75/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parse_c1d94c6a613ac216ea8a78424965ec75/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
